docker:
  image: "ubuntu-14.04-oracle-jdk8"
install:
  - "sudo apt-get install -y maven"
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |
    mvn release:prepare release:perform -B --settings /home/r/settings.xml